FROM ubuntu:22.04

CMD ["bash"]
EXPOSE 179/tcp

RUN apt-get update && apt-get install -y autoconf bison build-essential curl flex libreadline-dev libncurses5-dev m4 unzip

WORKDIR /root
RUN curl -O -L https://bird.network.cz/download/bird-2.0.11.tar.gz

RUN tar -zxvf bird-2.0.11.tar.gz

RUN mkdir /etc/bird
RUN cd bird-2.0.11 && autoconf && autoheader && ./configure && make && make install

CMD ["/bin/sh", "-c", "bird -c /etc/bird/bird.conf -d"]

