---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: general
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vm-fast
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Block
  storageClassName: general
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-public-ip
  labels:
    app.kubernetes.io/advertise: "true"
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    special: fedora-vm
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: fedora-public-ip
  labels:
    special: fedora-vm
spec:
  domain:
    ioThreadsPolicy: shared
    cpu:
      cores: 16
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
        cache: none
        dedicatedIOThread: true
      - disk:
          bus: virtio
        name: cloudinitdisk
      - disk:
          bus: virtio
        name: emptydisk
        dedicatedIOThread: true
        cache: none
      - disk:
          bus: virtio
        name: mypvcdisk
        dedicatedIOThread: true
        cache: none
      - disk:
          bus: virtio
        name: mypvcdiskfast
        dedicatedIOThread: true
        cache: none
    resources:
      requests:
        memory: 4Gi
        cpu: 16
  volumes:
  - name: mypvcdisk
    persistentVolumeClaim:
      claimName: pvc-vm
  - name: mypvcdiskfast
    persistentVolumeClaim:
      claimName: pvc-vm-fast
  - emptyDisk:
      capacity: 1Gi
    name: emptydisk
  - name: containerdisk
    containerDisk:
      image: quay.io/kubevirt/fedora-cloud-container-disk-demo:20210811_9fec1f849
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
