---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-cluster
spec:
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/management/cluster
    repoURL: git@github.com:ader1990/u5n-k8s-docs.git
    targetRevision: argocd-arm64-altra-flatcar-amd64hybrid
  ignoreDifferences:
  - group: infrastructure.cluster.x-k8s.io
    kind: TinkerbellCluster
    jsonPointers:
    - /spec/imageLookupBaseRegistry