---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.gitea.name }}
spec:
  destination:
    namespace: {{ .Values.gitea.namespace }}
    server: https://kubernetes.default.svc
  project: management
  source:
    chart: gitea
    repoURL: https://dl.gitea.io/charts/
    targetRevision: {{ .Values.gitea.version }}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.gitea.values | nindent 8 }}
  ignoreDifferences:
    - kind: Secret
      name: gitea-postgresql
      namespace: {{ .Values.gitea.namespace }}
      jsonPointers:
        - /data