---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/management/hardware
    repoURL: git@github.com:cloudbase/BMK.git
    targetRevision: flatcar_sysext