---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/management/hardware
    repoURL: git@github.com:ader1990/u5n-k8s-docs.git
    targetRevision: argocd-arm64-altra-flatcar-amd64hybrid