---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.tinkstack.name }}
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: {{ .Values.tinkstack.namespace }}
    server: https://kubernetes.default.svc
  project: management
  source:
    chart: stack
    repoURL: ghcr.io/tinkerbell/charts
    targetRevision: {{ .Values.tinkstack.version }}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.tinkstack.values | nindent 8 }}
