---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bm-auth-altra
  namespace: tink-system
spec:
  encryptedData:
    password: AgCOD1qalHgMyxvSju11UgJUD8qBAlyLQV5UYegadWb5C7TvE7RNgw1efmboIm7NskcjzY6jIIfrjzdXh7M4rv6d5WDp4CQUsSDyAELBSBwyQH6+9DWxlVsLYvAth12qVCpGfYWnrcGg5l/XJuBFKBGQvWFLiFBDQ7YLVCLeeH2RhNzeDl0nVG4Iq2Jz74cY/+PQW5dee5CcPjF+/+bdZ5Y2AXiDCthxYEfwZZq65COz0mBeQ3pSUOxqpenzEfGzXZ1DTHOobHu61s23GozLmzsxTyIp11VHPoPlvCtj/mANu3yDN2XYN/57wFSeQwdXs/z97EfpI3fSejVzd5Dydjf5M8jPWwwbs0RlXodab+r4D9rY8ZpDJeLcKxKbnMeepN+9PGE2PMIEKkXblZ7kdS9NHbTerpBkSLWxYHOhq4nyweenkpMcHDVYbcYip16KyZ8nvjQT4KVUyLHDndaT7RKy2f7YeHPdHdgvgGA9KEA+kddYQm7MXYpJCpbmRURBG54Rredxf4yxKupkPX6YNYWuJk4jnHsIw7LFbj2IbkQ9rB56BF17G+qLaCQaJV+JxxyREq4LihDdisAnH/JU7dbvKnBFGD+mc8eXTEa3rH3UfvS/4ogv4dHkbNWmGKkupPAp4faAJ7V0aVyPlT+7z6fBJmMTFNpiOa7JQ+TDrZaAlg9qi5DST4b+/uqnz5VRJUcAQr2/ew==
    username: AgBawh+uj3roxOInpgV/dxJQHgwDOpa8cvVnCyNYL61+2X/5eBwmN43p8dnh5cM2kMleCgStaYCnYQbndtkH6D3HKJDpEJwKL0j2EW3/FuuOp4hv+qKgwafsVXQR9dpHwlGNtarIO2Ci+slkivQPIMppdS7S+V9BNOICgqBdLxhcp8yN6zPpa9dEt/iXniLAha/L3FIzPY4Bk4wQwe33dD/Zh5zSIBMJoYuwjCndV05uQu+EWUpgOeTB497PyBMvTdyVq/iGdocAdBuapKImFgnQW8GUJrx+7L4MTpQh8vTaAmM0qwA0RKkKIw8y65VobGhZR/b1j2f8bflX9V0ItI++WV55QSobZaNRjrt4YuHsHrG6RJeay1pscIYc9H0P4eX+dhDQOLGf8jZfJC+bs9nByh/tKboV9BGGa01fIzYT6w5uvLcnwV10wQ2HFdRxs4RrWLubt/vHAdI9q995FhwYqO8fj7QnavCMLvhrUKPMTN3b65njfT6zJTIg7y/AemfoZ0dr1JD/wRuG+IpkHFvW9PZMW3GnkRKO2P6KeKGfz27DSmbaLAroWjI6DQ9QH3dpSHUgAgNR1q3mzl2N+AWOhXFphx2xTAofbzFpEjfQsU07Y7PVSh0NN2QMz7Tx4lCK4AkS6sFvc6vUpBFMCJmmLFnYjFu1NDZafyVhrFrAHPZJ0O33mX2dWkJA+ult9R78imgq7Q==
  template:
    metadata:
      creationTimestamp: null
      name: bm-auth-altra
      namespace: tink-system
    type: kubernetes.io/basic-auth
