apiVersion: bmc.tinkerbell.org/v1alpha1
kind: Machine
metadata:
  name: machine1
  namespace: tink-system
spec:
  connection:
    host: 192.168.56.1
    authSecretRef:
      name: bm-auth-altra
      namespace: tink-system
    insecureTLS: true
    providerOptions:
      ipmitool:
        port: 623
