apiVersion: bmc.tinkerbell.org/v1alpha1
kind: Job
metadata:
  name: job-power-reset-node2
  namespace: tink-system
spec:
  machineRef:
    name: kub-poc-worker
    namespace: tink-system
  tasks:
    - powerAction: "off"
    - oneTimeBootDeviceAction:
        device:
          - "pxe"
        efiBoot: true
    - powerAction: "on"