apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     kubernetes.io/os: linux
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 65200
   exportPodCIDR: true
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.100.3.50/32'
      peerASN: 65000
   serviceSelector:
     matchExpressions:
       - key: somekey
         operator: NotIn
         values: ['never-used-value']
         #matchLabels:
         #  app.kubernetes.io/advertise: "true"