---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdi-manifests
spec:
  destination:
    namespace: cdi
    server: https://10.8.10.151:6443
  project: default
  source:
    path: config/workload/cdi
    repoURL: git@github.com:cloudbase/BMK.git
    targetRevision: flatcar_sysext
