---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-manifests
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: kube-system
    server: https://192.168.56.151:6443
  project: default
  source:
    path: config/workload/cilium
    repoURL: git@github.com:ader1990/BMK.git
    targetRevision: cncf_tm_baremetal_kvm_2025