---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-manifests
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: kube-system
    server: https://10.8.10.151:6443
  project: default
  source:
    path: config/workload/cilium
    repoURL: git@github.com:ader1990/u5n-k8s-docs.git
    targetRevision: argocd-arm64-altra-flatcar-amd64hybrid