---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: kube-system
    server: https://10.8.10.151:6443
  project: default
  source:
    path: config/workload/kubevirt
    repoURL: git@github.com:cloudbase/BMK.git
    targetRevision: flatcar_sysext