---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.operator.name }}
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: {{ .Values.operator.namespace }}
    server: https://10.8.10.151:6443
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: {{ .Values.operator.version }}
    helm:
      valueFiles:
        - values.yaml
      values: |-
        {{- toYaml .Values.operator.values | nindent 8 }}
